config/routes.rb
Rails.application.routes.draw do
  delete "/author_books/:book_id/:author_id", to: "author_books#destroy"
  resources :author_books, except: [:destroy]
  resources :authors
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :author_books, dependent: :destroy
    has_many :books, through: :author_books

    validates :name, presence: true
    validates :birth_year, presence: true
    validates :birth_year, numericality: {only_integer: true}
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
    belongs_to :author
    belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :author_books, dependent: :destroy
    has_many :authors, through: :author_books

    validates :title, presence: true
    validates :pages, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/author_books_controller.rb
class AuthorBooksController < ApplicationController

def destroy
    @author_book = AuthorBook.find_by(author_id: params[:author_id], book_id: params[:book_id])
    @author_book.destroy
    redirect_to books_path
end

def create
    @author_book = AuthorBook.find_or_create_by(author_book_params)
    redirect_to book_path(@author_book.book)
end


private

def author_book_params
    params.require(:author_book).permit(:author_id, :book_id)
end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors = Author.all
    end

    def show
        @author = Author.find(params[:id])
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.create(author_params)

        if @author.valid?
            redirect_to author_path(@author)
        else
            flash[:error] = @author.errors.full_messages
            render :new
        end
    end

    def edit
        @author = Author.find(params[:id])
    end

    def update 
        @author = Author.find(params[:id])
        @author.update(author_params)
        if @author.valid?
            redirect_to author_path(@author)
        else
            flash[:error] = @author.errors.full_messages
            render :edit
        end
    end

    def destroy
        @author = Author.find(params[:id])
        @author.destroy
        redirect_to authors_path
    end

    private
    
    def author_params
        params.require(:author).permit(:name, :birth_year)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
        def index
            @books = Book.all
        end
    
        def show
            @book = Book.find(params[:id])
            @author_book = AuthorBook.new
        end
    
        def new
            @book = Book.new
        end
    
        def create
            @book = Book.create(book_params)
    
            if @book.valid?
                redirect_to book_path(@book)
            else
                flash[:error] = @book.errors.full_messages
                render :new
            end
        end
    
        def edit
            @book = Book.find(params[:id])
        end
    
        def update 
            @book = Book.find(params[:id])
            @book.update(book_params)
            if @book.valid?
                redirect_to book_path(@book)
            else
                flash[:error] = @book.errors.full_messages
                render :edit
            end
        end
    
        def destroy
            @book = Book.find(params[:id])
            @book.destroy
            redirect_to book_path
        end
    
        private
        
        def book_params
            params.require(:book).permit(:title, :pages, author_ids: [])
        end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_books_helper.rb
module AuthorBooksHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/edit.html.erb
<h1>Edit <%= @author.name %></h1>
<br>
<% if flash[:error] %>
    <% flash[:error].each do |err| %>
        <%= err %><br>
    <% end %>
    <% flash[:error] = nil %>
    <br><br>
<% end %>

<%= form_for @author do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :birth_year %>
    <%= f.text_field :birth_year %><br><br>
    <%= f.submit %>
<% end %>

app/views/authors/index.html.erb
<h1>Authors!</h1>
<br>
<%= link_to "New Author", new_author_path %>
<br>
<ul>
<% @authors.each do |author| %>
    <li><%= link_to author.name, author_path(author) %> (b. <%= author.birth_year %>)
<% end %>
</ul> 

app/views/authors/new.html.erb
<h1>New Author</h1>
<br>
<% if flash[:error] %>
    <% flash[:error].each do |err| %>
        <%= err %><br>
    <% end %>
    <% flash[:error] = nil %>
    <br><br>
<% end %>

<%= form_for @author do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :birth_year %>
    <%= f.text_field :birth_year %><br><br>
    <%= f.submit %>
<% end %>

app/views/authors/show.html.erb
<h1><%=@author.name%> (b. <%=@author.birth_year%>)</h1>
<br>
Books:
<ul>
<% @author.books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
<% end %>
</ul>
<%= link_to "Edit #{@author.name}", edit_author_path(@author) %>
<%= button_to "Delete #{@author.name}", author_path(@author), method: :delete %>

app/views/books/edit.html.erb
<h1>Edit <%= @author.name %></h1>
<br>
<% if flash[:error] %>
    <% flash[:error].each do |err| %>
        <%= err %><br>
    <% end %>
    <% flash[:error] = nil %>
    <br><br>
<% end %>

<%= form_for @author do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :birth_year %>
    <%= f.text_field :birth_year %><br><br>
    <%= f.submit %>
<% end %>

app/views/books/index.html.erb
<br>
<br>
<%= link_to "New Book", new_book_path %>
<br>
<h1>Books!</h1>
<br>
<ul>
<% @books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %> (<%= book.pages %> pages)
<% end %>
</ul> 

app/views/books/new.html.erb
<h1>New Author</h1>
<br>
<% if flash[:error] %>
    <% flash[:error].each do |err| %>
        <%= err %><br>
    <% end %>
    <% flash[:error] = nil %>
    <br><br>
<% end %>

<%= form_for @author do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :birth_year %>
    <%= f.text_field :birth_year %><br><br>
    <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%=@book.title%> (<%=@book.pages%> pages)</h1>
<br>
<h2>Authors:</h2>
<ul>
<% @book.authors.each do |author| %>
    <li><%= link_to "#{author.name} (b. #{author.birth_year})", author_path(author) %><br>
    <%= button_to "Remove author", "/author_books/#{@book.id}/#{author.id}", method: :delete %></li>
<% end %>
</ul>
<%= form_for @author_book do |f| %>
    <%= f.hidden_field :book_id, value: @book.id %>
    <%= f.label :author %>
    <%= f.collection_select :author_id, Author.all, :id, :name %>
    <%= f.submit "Add Author" %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIsFun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    1. <%=link_to "Authors Index", authors_path %><br>
    2. <%=link_to "Books Index", books_path %>

    <hr>
    <%= yield %>
  </body>
</html>